steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/testCloudBuildCICD/testCloudBuildCICD:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/testCloudBuildCICD/testCloudBuildCICD:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'testCloudBuildCICD', '--region=europe-west1', '--platform=managed', '--image=gcr.io/testCloudBuildCICD/testCloudBuildCICD:$SHORT_SHA']
  

